//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjVolunteer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class actsdetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actsdetail()
        {
            this.actenroll = new HashSet<actenroll>();
            this.timedetail = new HashSet<timedetail>();
        }
    
        public int actsdetail_id { get; set; }
        public string actsdetail_name { get; set; }
        public int activitytype_id { get; set; }
        public string actsdetail_icon { get; set; }
        public string actsdetail_address { get; set; }
        public decimal actsdetail_address_x { get; set; }
        public decimal actsdetail_address_y { get; set; }
        public string actsdetail_content { get; set; }
        public int actsdetail_predinum { get; set; }
        public int actsdetail_wantnum { get; set; }
        public int actsdetail_peoples { get; set; }
        public int actsdetail_applicantid { get; set; }
        public int actcondition_id { get; set; }
        public int clicks { get; set; }
        public System.DateTime act_enroll_endtime { get; set; }
        public System.DateTime act_enroll_starttime { get; set; }
        public System.DateTime act_starttime { get; set; }
        public System.DateTime art_endtime { get; set; }
        public System.DateTime actsdetail_createtime { get; set; }
        public int status_id { get; set; }
        public Nullable<int> updateid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string actsdetail_remarks { get; set; }
    
        public virtual actcondition actcondition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actenroll> actenroll { get; set; }
        public virtual activitytype activitytype { get; set; }
        public virtual organizeinfos organizeinfos { get; set; }
        public virtual status status { get; set; }
        public virtual userinfo userinfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timedetail> timedetail { get; set; }
    }
}
