//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjVolunteer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OjVolunteerEntities : DbContext
    {
        public OjVolunteerEntities()
            : base("name=OjVolunteerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actcondition> actcondition { get; set; }
        public virtual DbSet<actenroll> actenroll { get; set; }
        public virtual DbSet<activeindex> activeindex { get; set; }
        public virtual DbSet<activitytype> activitytype { get; set; }
        public virtual DbSet<actsdetail> actsdetail { get; set; }
        public virtual DbSet<change> change { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<favors> favors { get; set; }
        public virtual DbSet<major> major { get; set; }
        public virtual DbSet<organizeinfos> organizeinfos { get; set; }
        public virtual DbSet<political> political { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<talk> talk { get; set; }
        public virtual DbSet<timedetail> timedetail { get; set; }
        public virtual DbSet<userduration> userduration { get; set; }
        public virtual DbSet<userinfo> userinfo { get; set; }
        public virtual DbSet<userinte> userinte { get; set; }
    }
}
