//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjVolunteer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizeinfos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public organizeinfos()
        {
            this.actsdetail = new HashSet<actsdetail>();
            this.change = new HashSet<change>();
            this.userinfo = new HashSet<userinfo>();
        }
    
        public int organizeinfo_id { get; set; }
        public string organizeinfo_username { get; set; }
        public string organizeinfo_realname { get; set; }
        public string organizeinfo_password { get; set; }
        public string organizeinfo_people { get; set; }
        public string organizeinfo_phone { get; set; }
        public string organizeinfo_email { get; set; }
        public System.DateTime organizeinfo_lasttime { get; set; }
        public int status_id { get; set; }
        public Nullable<int> updateid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string organizeinfo_remarks { get; set; }
        public Nullable<int> f_organizeinfo_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actsdetail> actsdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<change> change { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userinfo> userinfo { get; set; }
    }
}
