//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjVolunteer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userinfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userinfo()
        {
            this.actenroll = new HashSet<actenroll>();
            this.actsdetail = new HashSet<actsdetail>();
            this.change = new HashSet<change>();
            this.favors = new HashSet<favors>();
            this.talk = new HashSet<talk>();
            this.timedetail = new HashSet<timedetail>();
            this.userduration = new HashSet<userduration>();
            this.userinte = new HashSet<userinte>();
        }
    
        public int userinfo_id { get; set; }
        public string userinfo_username { get; set; }
        public string userinfo_password { get; set; }
        public string userinfo_phone { get; set; }
        public string userinfo_studentid { get; set; }
        public string userinfo_realname { get; set; }
        public Nullable<int> major_id { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> political_id { get; set; }
        public Nullable<int> organizeinfo_id { get; set; }
        public string userinfo_email { get; set; }
        public System.DateTime userinfo_lasttiem { get; set; }
        public int status_id { get; set; }
        public Nullable<int> updateid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string userinfo_remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actenroll> actenroll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actsdetail> actsdetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<change> change { get; set; }
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favors> favors { get; set; }
        public virtual major major { get; set; }
        public virtual organizeinfos organizeinfos { get; set; }
        public virtual political political { get; set; }
        public virtual status status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<talk> talk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timedetail> timedetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userduration> userduration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userinte> userinte { get; set; }
    }
}
