//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjVolunteer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class favors
    {
        public int favor_id { get; set; }
        public int talk_id { get; set; }
        public int userinfo_id { get; set; }
        public System.DateTime favor_time { get; set; }
    
        public virtual talk talk { get; set; }
        public virtual userinfo userinfo { get; set; }
    }
}
