//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjVolunteer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class talk
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public talk()
        {
            this.favors = new HashSet<favors>();
        }
    
        public int talk_id { get; set; }
        public int userinfo_id { get; set; }
        public string talk_content { get; set; }
        public System.DateTime talk_time { get; set; }
        public int talk_favor { get; set; }
        public int status_id { get; set; }
        public Nullable<int> updataid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string talk_remarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<favors> favors { get; set; }
        public virtual status status { get; set; }
        public virtual userinfo userinfo { get; set; }
    }
}
