//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OjVolunteer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userduration
    {
        public int userduration_id { get; set; }
        public int userinfo_id { get; set; }
        public decimal tatallength { get; set; }
        public decimal propartytimelength { get; set; }
        public decimal partytimelength { get; set; }
        public System.DateTime userduration_createtime { get; set; }
        public System.DateTime propartytime { get; set; }
        public System.DateTime partytime { get; set; }
        public Nullable<int> updateid { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string userduration_remarks { get; set; }
    
        public virtual userinfo userinfo { get; set; }
    }
}
